### ISSUE TITLE
Feature request: xnos-non-breaking customisation

### ISSUE THREAD

**Issue by stroobandt** [tomduck/pandoc-xnos#14]
This is a feature request for a general `xnos-non-breaking` customisation,
with child customisations `fignos-non-breaking`,  `tablenos-non-breaking`, etc.

Setting this `--metadata` variable to `True`,

    -M xnos-non-breaking=True

would replace the standard whitespace between, for example, "Fig. 1" with a [**non-breaking space**](https://en.wikipedia.org/wiki/Non-breaking_space) in the different output formats. That would be `~` for LaTeX, `&nbsp;` for (X)HTML, and `U+00A0` in Unicode.

This should affect all names; i.e. `xnos-plus-name`, `xnos-star-name` and `xnos-caption-name`.

However, this should not affect the `xnos-caption-separator`, which is already controlled separately.
Adding `non-breaking` as an allowed value for `xnos-caption-separator` would take care of this specific caption separator.

**Comment by stroobandt** [comment]
[This pull request](https://github.com/tomduck/pandoc-xnos/pull/12) would solve my issue with the lack of non-breaking spaces in (X)HTML.

**Comment by tomduck** [comment]
Thank you for the pull request.  I have merged it into the `nextrelease` branch.

**Comment by timtroendle** [comment]
As [mentioned in pandoc-fignos](https://github.com/tomduck/pandoc-fignos/issues/78#issuecomment-667816743), this feature does not work in pandoc-xnos 2.4.2

**Comment by tomduck** [comment]
My bad.  I didn't realize that a unicode space character was being used in the code.  I am finalizing a fix that will make this explicit, and will generalize it to work with both python 2.7 and 3.x.  --Tom

**Comment by tomduck** [comment]
@timtroendle: I just released pandoc-xnos 2.4.3.  Could you please upgrade to it and confirm the nonbreaking space issue is resolved?  Thanks, Tom.

**Comment by stroobandt** [comment]
@tomduck I tested `pandoc-xnos 2.4.3`. Unfortunately, I am still not seeing any `&nbsp;` in the HTML output. Mind you, I am using the `-M xnos-cleveref=True` customisation.

**Comment by timtroendle** [comment]
@stroobandt There is no `&nbsp;` in the html, but there _is_ a non-breaking space. [Pandoc uses the unicode character instead of `&nbsp;`](https://github.com/jgm/pandoc/pull/6201/files) -- which looks almost like a normal whitespace. You can confirm it's non breaking by using an editor that can display it (e.g. VSCode) or by rendering it in the browser (I am using Safari).

So @tomduck I from my side would confirm it works with HTML, thanks for the quick fix. However, it doesn't seem to work when using Weasyprint to generate a PDF. I am not quite sure why at the moment and will need to have another look.

**Comment by stroobandt** [comment]
@tomduck Sorry, my bad, Tom. I can confirm the clever references for figures and tables now contain the UTF-8 `0x00a0` non-breaking space in HTML. I checked it with the `ga` command in `gvim` on Linux.

For good measure, the `pandoc-xnos` generated `<p class="caption"><span>Figure 1:</span>` contains an ordinary space. This does not bother me personally, but might affect other users.

**Comment by tomduck** [comment]
All good.  Pandoc's use of a nonbreaking unicode space also took me by surprise.  Thanks, @timtroendle, for linking in when this change to pandoc's documentation was made.

@stroobandt, this is a good point that there should also be a nonbreaking space between the reference name and number in the caption.  I have made the required changes in pandoc-fignos and pandoc-tablenos, and pushed the results to the `nextrelease` branch of each.

@timtroendle, I will keep this Issue open while you investigate the interaction with WeasyPrint.

Thanks to you both for your help.

**Comment by timtroendle** [comment]
@tomduck Regarding weasyprint, it turns out this is an issue on their side (see https://github.com/Kozea/WeasyPrint/issues/1185) that only occurs when the Figure number is a link. When I use a `{nolink=True}` to avoid the link, the resulting PDF looks fine.

**Comment by stroobandt** [comment]
@timtroendle Let us close this issue then, to prevent further confusion.

**Comment by tomduck** [comment]
Thanks for the update, @timtroendle.  And thanks to you both for your help.  :o)  Cheers, Tom.
